{
  "runOn": [
    {
      "minServerVersion": "4.0",
      "topology": [
        "single",
        "replicaset"
      ]
    },
    {
      "minServerVersion": "4.1.7",
      "topology": [
        "sharded"
      ]
    }
  ],
  "database_name": "retryable-reads-tests",
  "collection_name": "coll",
  "data": [
    {
      "_id": 1,
      "x": 11
    },
    {
      "_id": 2,
      "x": 22
    }
  ],
  "tests": [
    {
      "description": "Count succeeds after InterruptedAtShutdown",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 11600
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "result": 2
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Count succeeds after InterruptedDueToReplStateChange",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 11602
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "result": 2
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Count succeeds after NotMaster",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 10107
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "result": 2
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Count succeeds after NotMasterNoSlaveOk",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 13435
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "result": 2
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Count succeeds after NotMasterOrSecondary",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 13436
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "result": 2
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Count succeeds after PrimarySteppedDown",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 189
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "result": 2
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Count succeeds after ShutdownInProgress",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 91
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "result": 2
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Count succeeds after HostNotFound",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 7
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "result": 2
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Count succeeds after HostUnreachable",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 6
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "result": 2
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Count succeeds after NetworkTimeout",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 89
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "result": 2
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Count succeeds after SocketException",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 9001
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "result": 2
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Count fails after two NotMaster errors",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 2
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 10107
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "error": true
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Count fails after NotMaster when retryReads is false",
      "clientOptions": {
        "retryReads": false
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "count"
          ],
          "errorCode": 10107
        }
      },
      "operations": [
        {
          "name": "count",
          "object": "collection",
          "arguments": {
            "filter": {}
          },
          "error": true
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "count": "coll"
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    }
  ]
}
