{
  "runOn": [
    {
      "minServerVersion": "4.0",
      "topology": [
        "single",
        "replicaset"
      ]
    },
    {
      "minServerVersion": "4.1.7",
      "topology": [
        "sharded"
      ]
    }
  ],
  "database_name": "retryable-reads-tests",
  "collection_name": "coll",
  "data": [
    {
      "_id": 1,
      "x": 11
    },
    {
      "_id": 2,
      "x": 22
    },
    {
      "_id": 3,
      "x": 33
    }
  ],
  "tests": [
    {
      "description": "Distinct succeeds after InterruptedAtShutdown",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 11600
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "result": [
            22,
            33
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Distinct succeeds after InterruptedDueToReplStateChange",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 11602
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "result": [
            22,
            33
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Distinct succeeds after NotMaster",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 10107
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "result": [
            22,
            33
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Distinct succeeds after NotMasterNoSlaveOk",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 13435
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "result": [
            22,
            33
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Distinct succeeds after NotMasterOrSecondary",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 13436
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "result": [
            22,
            33
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Distinct succeeds after PrimarySteppedDown",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 189
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "result": [
            22,
            33
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Distinct succeeds after ShutdownInProgress",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 91
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "result": [
            22,
            33
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Distinct succeeds after HostNotFound",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 7
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "result": [
            22,
            33
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Distinct succeeds after HostUnreachable",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 6
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "result": [
            22,
            33
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Distinct succeeds after NetworkTimeout",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 89
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "result": [
            22,
            33
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Distinct succeeds after SocketException",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 9001
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "result": [
            22,
            33
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Distinct fails after two NotMaster errors",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 2
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 10107
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "error": true
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Distinct fails after NotMaster when retryReads is false",
      "clientOptions": {
        "retryReads": false
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "distinct"
          ],
          "errorCode": 10107
        }
      },
      "operations": [
        {
          "name": "distinct",
          "object": "collection",
          "arguments": {
            "fieldName": "x",
            "filter": {
              "_id": {
                "$gt": 1
              }
            }
          },
          "error": true
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "distinct": "coll",
              "key": "x",
              "query": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    }
  ]
}
